- task: NodeTool@0
  inputs:
    versionSpec: '20.13.1'
  displayName: 'Install node.js'

- script: |
    npm install -g @angular/cli
    npm install
  displayName: 'Install Angular dependencies'

- script: |
    npm run build -- --configuration=production
  displayName: 'Build Angular app'

# ✅ Publish dist/pfefrontend folder (NOT a ZIP)
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'dist/pfefrontend'
    ArtifactName: 'drop'
    publishLocation: 'Container'
  displayName: 'Publish dist folder'
