trigger:
  - main
 
pool:
  name: Default
 
steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '22.13.1'
    displayName: 'Install Node.js'
 
  - script: |
      echo "Node version:"
      node -v
      echo "NPM version:"
      npm -v
      echo "Current directory:"
      cd
      echo "Directory contents:"
      dir
    displayName: 'Environment Info'
   
  - script: |
      npm config set strict-ssl false
      npm config set registry https://registry.npmjs.org/
      npm config set fetch-retries 100
      npm config set fetch-retry-mintimeout 60000
      npm config set fetch-retry-maxtimeout 300000
      npm config set timeout 0
      npm ci
    displayName: 'Install Dependencies'
   
  - script: |
      echo "Contents of package.json:"
      type package.json
      echo "Angular.json contents:"
      type angular.json
      npm run build --prod
    displayName: 'Build Angular App'
   
  - script: |
      echo "Directory after build:"
      dir
      echo "Dist directory contents (if exists):"
      dir dist 2>nul || echo "Dist directory not found"
      echo "Looking for any dist-like directories:"
      dir /s /b | findstr dist
    displayName: 'Check Build Output'
    condition: succeededOrFailed()
 
  - task: AzureWebApp@1
    inputs:
      azureSubscription: 'azure-connection-pfe'
      appName: 'pfe-frontend-app'
      package: '$(System.DefaultWorkingDirectory)/dist/*'
    displayName: 'Deploy to Azure Web App'
    condition: succeeded()
