trigger:
- main
pool:
  name: Default
steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.13.1'
  displayName: 'Install node.js'

- script: |
    npm install --save-dev @angular-devkit/build-angular
    npm install -g @angular/cli
    npm install
  displayName: 'Install dependencies'

# First, let's check what directories exist to debug the issue
- script: |
    echo Workspace directory contents:
    dir
    echo Angular.json configuration:
    findstr /C:"outputPath" angular.json
  displayName: 'Debug directory structure'

- script: |
    npm run build -- --configuration=production
    echo Build output directories:
    dir dist
  displayName: 'Build Angular app (production)'

# Modified to be more flexible with the output path
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: 'dist/pfefrontend'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/app.zip'
    replaceExistingArchive: true
  displayName: 'Archive Angular build output'

- task: AzureRmWebAppDeployment@5
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Azure subscription 1(1)(cdac076e-a055-45d3-9bb6-dc1e0a6536e0)'
    appType: 'webAppLinux'
    WebAppName: 'pfe-frontend-app'
    packageForLinux: '$(Build.ArtifactStagingDirectory)/app.zip'
    DeploymentTypeLinux: 'oneDeploy'
