trigger:
- main
pool:
  name: Default
steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.13.1'
  displayName: 'Install node.js'

- script: |
    npm install --save-dev @angular-devkit/build-angular
    npm install -g @angular/cli
    npm install
  displayName: 'Install dependencies'

# First, let's check what directories exist to debug the issue
- script: |
    echo Workspace directory contents:
    dir
    echo Angular.json configuration:
    findstr /C:"outputPath" angular.json
  displayName: 'Debug directory structure'

- script: |
    npm run build -- --configuration=production
    echo Build output directories:
    dir dist
  displayName: 'Build Angular app (production)'

# Modified to be more flexible with the output path
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: 'dist'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/app.zip'
    replaceExistingArchive: true
  displayName: 'Archive Angular build output'

# Déploiement vers Azure App Service
- task: AzureWebApp@1
  inputs:
    azureSubscription: 'azure-connection-pfe'
    appName: 'pfe-frontend-app'
    package: '$(Build.ArtifactStagingDirectory)/app.zip'
  displayName: 'Deploy Angular app to Azure Web App'
