trigger:
  - main

pool:
  name: self 

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '20.13.1'
    displayName: 'Install Node.js'

  - script: |
      npm install --save-dev @angular-devkit/build-angular
      npm install -g @angular/cli
      npm install
    displayName: 'Install Angular dependencies'

  - script: |
      echo Workspace directory contents:
      dir
      echo Angular.json configuration:
      findstr /C:"outputPath" angular.json
    displayName: 'Debug directory structure'

  - script: |
      npm run build -- --configuration=production
      echo Build output directories:
      dir dist
    displayName: 'Build Angular app (production)'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: 'dist/pfefrontend'
      ArtifactName: 'drop'
      publishLocation: 'Container'
    displayName: 'Publish dist folder'
