trigger:
- main  # Trigger the pipeline when code is pushed to the main branch

pool:
  name: Default  # Use the latest Ubuntu agent

variables:
  buildConfiguration: 'prod'  # Environment-specific config (optional)

steps:
- script: |
    npm install
    npm run build-prod
    echo Workspace directory contents:
    dir
    dir dist
  displayName: 'Build Angular App'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: 'dist'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/app.zip'
    replaceExistingArchive: true
  displayName: 'Archive Entire dist folder including server files'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/app.zip'
    ArtifactName: 'drop'
    publishLocation: 'Container'
  displayName: 'Publish Artifact to be used in Release pipeline'
