trigger:
- main

pool:
  name: Default

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.13.1'
  displayName: 'Install Node.js'

- script: |
    npm install --save-dev @angular-devkit/build-angular
    npm install -g @angular/cli
    npm install
  displayName: 'Install dependencies'

- script: npm run build -- --configuration=production
  displayName: 'Build Angular app (production)'


# Archive les fichiers de build Angular
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: 'dist/pfe-frontend/browser'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/app.zip'
    replaceExistingArchive: true
  displayName: 'Archive Angular build output'

# Déploiement vers Azure App Service
- task: AzureWebApp@1
  inputs:
    azureSubscription: 'azure-connection-pfe'
    appName: 'pfe-frontend-app'
    package: '$(Build.ArtifactStagingDirectory)/app.zip'
  displayName: 'Deploy Angular app to Azure Web App'
